/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 - Kalyo Connect Theme
        'on-surface': '#191b25',
        'inverse-surface': '#2e303a',
        'background': '#fbf8ff',
        'surface-container-high': '#e7e7f5',
        'on-tertiary-fixed-variant': '#891e00',
        'tertiary-fixed': '#ffdbd2',
        'tertiary-container': '#bf3003',
        'surface-tint': '#004af1',
        'primary': '#003dc9',
        'on-secondary-container': '#253b8a',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'error': '#ba1a1a',
        'on-secondary-fixed': '#001453',
        'tertiary': '#952200',
        'primary-fixed-dim': '#b8c4ff',
        'on-primary-fixed': '#001453',
        'on-primary-container': '#dfe3ff',
        'on-background': '#191b25',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#0037b9',
        'tertiary-fixed-dim': '#ffb4a1',
        'surface-container-low': '#f3f2ff',
        'surface-bright': '#fbf8ff',
        'secondary': '#4559a9',
        'surface-container': '#ededfb',
        'outline': '#737688',
        'inverse-on-surface': '#f0effd',
        'primary-container': '#0951ff',
        'outline-variant': '#c3c5d9',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#b7c4ff',
        'on-error-container': '#93000a',
        'surface-variant': '#e1e1ef',
        'on-surface-variant': '#434656',
        'on-secondary-fixed-variant': '#2b4090',
        'surface-container-highest': '#e1e1ef',
        'secondary-fixed': '#dde1ff',
        'on-secondary': '#ffffff',
        'surface': '#fbf8ff',
        'on-tertiary-fixed': '#3c0800',
        'on-error': '#ffffff',
        'primary-fixed': '#dde1ff',
        'surface-dim': '#d9d9e6',
        'secondary-container': '#96a9ff',
        'on-tertiary-container': '#ffddd5',
        'inverse-primary': '#b8c4ff',
        'sky-blue': '#38bdf8',
        'vivid-red': '#ef4444',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'display': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Plus Jakarta Sans', 'sans-serif'],
        'label': ['Plus Jakarta Sans', 'sans-serif'],
      },
      animation: {
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'flow': 'flow 2s linear infinite',
      },
      keyframes: {
        flow: {
          'from': { 'stroke-dashoffset': '100' },
          'to': { 'stroke-dashoffset': '0' },
        }
      }
    },
  },
  plugins: [],
}

